AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Infinite Dialogue - LLM Chat Backend Infrastructure

Parameters:
  GoogleModelName:
    Type: String
    Default: gemini-2.0-flash-lite-preview-02-05
    Description: Google AI Model Name
  Environment:
    Type: String
    Default: prod
    AllowedValues: [local, prod]
    Description: Environment type (local for SAM local, prod for AWS deployment)

Conditions:
  IsLocalEnvironment: !Equals [!Ref Environment, local]

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256

Resources:
  # DynamoDB Table for Chat Messages
  ILChatChatLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ILChat_ChatLog
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: datetime
          AttributeType: N
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: datetime
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SenderEmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: datetime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # DynamoDB Table for News Cache
  ILChatNewsCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ILChat_NewsAPI_Cache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: request_hash
          AttributeType: S
      KeySchema:
        - AttributeName: request_hash
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # Lambda Function
  ILChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ILChat_MainHandler
      CodeUri: .
      Handler: index.handler
      Description: Infinite Dialogue main Lambda handler
      Environment:
        Variables:
          GOOGLE_API_KEY: '{{resolve:ssm:/ILChat/GoogleApiKey}}'
          GOOGLE_MODEL_NAME: !Ref GoogleModelName
          VITE_GOOGLE_CLIENT_ID: '{{resolve:ssm:/ILChat/GoogleClientId}}'
          VITE_GNEWS_API_KEY: '{{resolve:ssm:/ILChat/GNewsApiKey}}'
          CHAT_TABLE_NAME: !Ref ILChatChatLogTable
          NEWS_TABLE_NAME: !Ref ILChatNewsCacheTable
          IS_LOCAL: !If [IsLocalEnvironment, "true", !Ref "AWS::NoValue"]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ILChatChatLogTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ILChatNewsCacheTable
        - SSMParameterReadPolicy:
            ParameterName: ILChat/*
      Events:
        GetChat:
          Type: HttpApi
          Properties:
            Path: /getchat
            Method: GET
            ApiId: !Ref ILChatHttpApi
        GetNews:
          Type: HttpApi
          Properties:
            Path: /news
            Method: GET
            ApiId: !Ref ILChatHttpApi
        InitChat:
          Type: HttpApi
          Properties:
            Path: /init-chat
            Method: GET
            ApiId: !Ref ILChatHttpApi
        ProcessInput:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            ApiId: !Ref ILChatHttpApi

  # Orchestrator Lambda Function
  ILChatOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ILChat_Orchestrator
      CodeUri: .
      Handler: orchestrator.handler
      Description: Infinite Dialogue orchestrator for managing AI responses
      Timeout: 60
      Environment:
        Variables:
          GOOGLE_API_KEY: '{{resolve:ssm:/ILChat/GoogleApiKey}}'
          GOOGLE_MODEL_NAME: !Ref GoogleModelName
          ANTHROPIC_API_KEY: '{{resolve:ssm:/ILChat/AnthropicApiKey}}'
          OPENAI_API_KEY: '{{resolve:ssm:/ILChat/OpenAIApiKey}}'
          CHAT_TABLE_NAME: !Ref ILChatChatLogTable
          IS_LOCAL: !If [IsLocalEnvironment, "true", !Ref "AWS::NoValue"]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ILChatChatLogTable
        - SSMParameterReadPolicy:
            ParameterName: ILChat/*

  # EventBridge Scheduler for Orchestrator
  ILChatOrchestratorSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: ILChat-Orchestrator-Schedule
      Description: Triggers the orchestrator Lambda every 2 minutes
      ScheduleExpression: rate(2 minutes)
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt ILChatOrchestratorFunction.Arn
        RoleArn: !GetAtt ILChatSchedulerRole.Arn

  # IAM Role for EventBridge Scheduler
  ILChatSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ILChat-Scheduler-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt ILChatOrchestratorFunction.Arn

  # Lambda Permission for EventBridge Scheduler
  ILChatOrchestratorInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ILChatOrchestratorFunction
      Action: lambda:InvokeFunction
      Principal: scheduler.amazonaws.com
      SourceArn: !GetAtt ILChatOrchestratorSchedule.Arn

  # HTTP API Gateway
  ILChatHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Authorization
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - OPTIONS

Outputs:
  ApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${ILChatHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ILChatFunction.Arn
  OrchestratorFunctionArn:
    Description: Orchestrator Lambda Function ARN
    Value: !GetAtt ILChatOrchestratorFunction.Arn
  ChatLogTableName:
    Description: DynamoDB Chat Log Table Name
    Value: !Ref ILChatChatLogTable
  NewsCacheTableName:
    Description: DynamoDB News Cache Table Name
    Value: !Ref ILChatNewsCacheTable
  SchedulerArn:
    Description: EventBridge Scheduler ARN
    Value: !GetAtt ILChatOrchestratorSchedule.Arn
